CREATE TABLE IF NOT EXISTS `PRODUCTS_AUX` (
	  `ID` varchar(255) NOT NULL,
	  `PRODUCT` varchar(255) NOT NULL,
	  `PRODUCT_AUX` varchar(255) NOT NULL,
	  PRIMARY KEY (`ID`),
	  CONSTRAINT `PRODUCTS_AUX_FK_1` FOREIGN KEY (`PRODUCT`) REFERENCES `PRODUCTS` (`ID`),
	  CONSTRAINT `PRODUCTS_AUX_FK_2` FOREIGN KEY (`PRODUCT_AUX`) REFERENCES `PRODUCTS` (`ID`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;
